import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>WordPress po polsku</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Image src="/logo.png" alt="Logo" width={256} height={256} />
        <h1 className={styles.title}>
          <big>WordPress</big> po polsku
        </h1>
        <p>Nowy kanał na YouTube</p>
        <p>
          <strong>
            Praktyczna wiedza i ciekawostki od WordPress developera dla
            WordPress developerów po polsku!
          </strong>
        </p>
        <p>Premiera pierwszego filmu w poniedziałek o godzinie 20:00!</p>
        <p>
          <a
            href="https://www.youtube.com/@wordpresspopolsku/featured"
            className={styles.cta}
            target="_blank"
          >
            Sprawdź na YouTube
          </a>
        </p>
      </main>
    </>
  );
}
